import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

import { AuthProvider } from './Provider';

export const metadata = {
  title: 'Next-auth project',
  description: 'Generated by create next-auth app',
};

export default function RootLayout({ children }) {
  return (
    React.createElement('html', {lang: 'en'},
      React.createElement('body', { className: inter.className },
        React.createElement(AuthProvider, null, children)
      )
    )
  );
}
